# Commented sections below can be used to run tests on the CI server
# https://simulatedgreg.gitbooks.io/electron-vue/content/en/testing.html#on-the-subject-of-ci-testing
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: "10"
    env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    language: node_js
    node_js: "10"
    services:
      - xvfb
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - libgnome-keyring-dev
          - rpm
          - bsdtar
          - g++-8
          - g++-multilib
          - icnsutils
          - graphicsmagick
          - xz-utils
          - xorriso
          - rpm
cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-8"; fi
install:
  - yarn --ignore-engines
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      /sbin/start-stop-daemon \
      --start \
      --quiet \
      --pidfile /tmp/custom_xvfb_99.pid \
      --make-pidfile \
      --background \
      --exec /usr/bin/Xvfb \
      -- :99 -ac -screen 0 1280x1024x16
    else
      :
    fi

script:
  - yarn fetch-dep && yarn run electron:build
if: tag IS blank